package FrondEnd;

import BackEnd.Conexion;
import BackEnd.CMenu;
import BackEnd.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Alrjandro Padilla
 */
public class Menu extends javax.swing.JFrame {

    Conexion cx;
    private int caja;
    private int seguro = 0;
    private String user;
    CMenu menu = new CMenu();
    public Menu(String user,int caja) {
        initComponents();
        setLocationRelativeTo(null); // Centra la ventana
        cx = new Conexion("TIENDA");
        this.caja=caja;
        this.user=user;
        //QUITAR EL FONDO DEL BOTON SALIR
        btnSalir.setBackground(new Color(0, 0, 0, 0));
        btnSalir.setBorderPainted(false); 
        btnSalir.setFocusPainted(false); 
        btnSalir.setContentAreaFilled(false);
        //QUITAR EL FONDO DEL BOTON REGRESAR
        btnRegresar.setBackground(new Color(0, 0, 0, 0));
        btnRegresar.setBorderPainted(false); 
        btnRegresar.setFocusPainted(false); 
        btnRegresar.setContentAreaFilled(false);
        //QUITAR EL FONDO DEL BOTON ABRIR
        btnAbrirC.setBackground(new Color(0, 0, 0, 0));
        btnAbrirC.setBorderPainted(false); 
        btnAbrirC.setFocusPainted(false); 
        btnAbrirC.setContentAreaFilled(false);
        //QUITAR EL FONDO DEL BOTON CERRAR
        btnCerrarT.setBackground(new Color(0, 0, 0, 0));
        btnCerrarT.setBorderPainted(false); 
        btnCerrarT.setFocusPainted(false); 
        btnCerrarT.setContentAreaFilled(false);
        txtNameCajero.setText(menu.name(user)); 
        
    }

    public Menu() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        lblNameCajero = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        cbxCajas = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTITULO = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnAbrirC = new javax.swing.JButton();
        btnCerrarT = new javax.swing.JButton();
        lblSalir = new javax.swing.JLabel();
        lblSalir1 = new javax.swing.JLabel();
        lblSalir2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSaldo1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtRol = new javax.swing.JTextField();
        txtSaldoI = new javax.swing.JTextField();
        lblSaldo2 = new javax.swing.JLabel();
        txtSaldoIF = new javax.swing.JTextField();
        txtNameCajero = new javax.swing.JTextField();
        btnVPeriodo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpleados.setBackground(new java.awt.Color(204, 204, 255));
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleado-de-oficina (1).png"))); // NOI18N
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 90, 70));

        btnProductos.setBackground(new java.awt.Color(204, 204, 255));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar-producto.png"))); // NOI18N
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 90, 70));

        btnVenta.setBackground(new java.awt.Color(204, 204, 255));
        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/venta.png"))); // NOI18N
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 70));

        lblNameCajero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNameCajero.setText("Nombre:");
        jPanel1.add(lblNameCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        lblRol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRol.setText("Rol:");
        lblRol.setToolTipText("");
        lblRol.setFocusTraversalPolicyProvider(true);
        jPanel1.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        cbxCajas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        cbxCajas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Caja 1", "Caja 2", "Caja 3" }));
        cbxCajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCajasActionPerformed(evt);
            }
        });
        jPanel1.add(cbxCajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 210, 40));

        btnRegresar.setBackground(new java.awt.Color(153, 153, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 60, 50));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        lblTITULO.setBackground(new java.awt.Color(153, 102, 255));
        lblTITULO.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTITULO.setForeground(new java.awt.Color(204, 204, 255));
        lblTITULO.setText("Menu");
        lblTITULO.setToolTipText("");

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAbrirC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/open.png"))); // NOI18N
        btnAbrirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirCActionPerformed(evt);
            }
        });

        btnCerrarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/close.png"))); // NOI18N
        btnCerrarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarTActionPerformed(evt);
            }
        });

        lblSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(204, 204, 255));
        lblSalir.setText("Salir");

        lblSalir1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblSalir1.setForeground(new java.awt.Color(204, 204, 255));
        lblSalir1.setText("Cerrar Turno");

        lblSalir2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblSalir2.setForeground(new java.awt.Color(204, 204, 255));
        lblSalir2.setText("Abrir Turno");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblTITULO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(btnAbrirC, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnCerrarT, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSalir1)
                        .addGap(31, 31, 31)))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnAbrirC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTITULO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnCerrarT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSalir)
                        .addComponent(lblSalir1))
                    .addComponent(lblSalir2))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 120));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Cajas:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        lblSaldo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldo1.setText("Saldo Final:");
        lblSaldo1.setToolTipText("");
        lblSaldo1.setFocusTraversalPolicyProvider(true);
        jPanel1.add(lblSaldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("PRODUCTOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("EMPLEADOS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("VENTA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        txtRol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(txtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 210, 40));

        txtSaldoI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(txtSaldoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 210, 40));

        lblSaldo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSaldo2.setText("Saldo Inicial:");
        lblSaldo2.setToolTipText("");
        lblSaldo2.setFocusTraversalPolicyProvider(true);
        jPanel1.add(lblSaldo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        txtSaldoIF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.add(txtSaldoIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 210, 40));

        txtNameCajero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNameCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameCajeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtNameCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 210, 40));

        btnVPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vperiodo.png"))); // NOI18N
        btnVPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVPeriodoActionPerformed(evt);
            }
        });
        jPanel1.add(btnVPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, 70));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("VENTA POR PERIODO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/giphy.gif"))); // NOI18N
        jPanel1.add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 480, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        this.seguro++;
        switch (seguro) {
            case 1 -> JOptionPane.showMessageDialog(null, "¿Estás seguro? ");
            case 2 -> JOptionPane.showMessageDialog(null, "¿Pero bien seguro? ");
            case 3 -> {
                cx.conectar();
                cx.desconectar();
                System.exit(0);
                seguro = 0; 
            }
            default -> {
            }
        }
        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        if (caja == 0) {
            Login login = new Login();
            login.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this,"Cierra primero el turno");
        }
        
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAbrirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirCActionPerformed
    
        if(caja == 0){
            if (cbxCajas.getSelectedIndex() != 0) {
                if (!"".equalsIgnoreCase(txtSaldoI.getText())) {
                    if (Integer.parseInt(txtSaldoI.getText()) >= 500) {
                        JOptionPane.showMessageDialog(this,"Se abrio caja exitosamente");
                        txtSaldoI.setText("");
                        txtRol.setText("");
                        caja = 1;
                    }else{
                        JOptionPane.showMessageDialog(this,"El saldo es menor a lo esperado: 500");
                    }     
                }else{
                    JOptionPane.showMessageDialog(this,"Inserta el Saldo Inicial");
                }
            }else{
                JOptionPane.showMessageDialog(this,"Escoge tu caja asignada");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Ya se abrio el turno");
        }
    }//GEN-LAST:event_btnAbrirCActionPerformed

    private void cbxCajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCajasActionPerformed
        int rol = cbxCajas.getSelectedIndex();
     
        switch (rol) {
            case 0 -> txtRol.setText("");
            case 1 -> txtRol.setText("CAJERO MATUTINO");
            case 2 -> txtRol.setText("CAJERO VESPERTINO");
            case 3 -> txtRol.setText("CAJERO NOCTURNO");
            default -> {
            }
        }
    }//GEN-LAST:event_cbxCajasActionPerformed

    private void btnCerrarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarTActionPerformed
        if (!"".equalsIgnoreCase(txtSaldoIF.getText())) {
            if(caja == 1){
                JOptionPane.showMessageDialog(this,"Se cerro caja exitosamente");
                cbxCajas.setSelectedIndex(0);
                caja = 0;
            }else{
                JOptionPane.showMessageDialog(this,"Ya se cerro el turno");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Ingresa la venta del dia");
        }
            
    }//GEN-LAST:event_btnCerrarTActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        if (caja==1) {
            Ventas_cajas venta = new Ventas_cajas(user,caja);
            venta.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this,"Abre primero tu turno");
        }
        
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        if (caja==1) {
            Agregar_P p = new Agregar_P(user,caja);
            p.setVisible(true);
            this.setVisible(false);
            System.out.println(caja);
        }else{
            JOptionPane.showMessageDialog(this,"Abre primero tu turno");
        }
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
       Empleados E=new Empleados();
       E.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void txtNameCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameCajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameCajeroActionPerformed

    private void btnVPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVPeriodoActionPerformed
        if (caja==1) {
            Venta_Periodo p = new Venta_Periodo(user,caja);
            p.setVisible(true);
            this.setVisible(false);
            System.out.println(caja);
        }else{
            JOptionPane.showMessageDialog(this,"Abre primero tu turno");
        }
    }//GEN-LAST:event_btnVPeriodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirC;
    private javax.swing.JButton btnCerrarT;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVPeriodo;
    private javax.swing.JButton btnVenta;
    private javax.swing.JComboBox<String> cbxCajas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblNameCajero;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblSaldo1;
    private javax.swing.JLabel lblSaldo2;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblSalir1;
    private javax.swing.JLabel lblSalir2;
    private javax.swing.JLabel lblTITULO;
    private javax.swing.JTextField txtNameCajero;
    private javax.swing.JTextField txtRol;
    private javax.swing.JTextField txtSaldoI;
    private javax.swing.JTextField txtSaldoIF;
    // End of variables declaration//GEN-END:variables
}
